baseurl = "https://gideonpyzer.com/"
languageCode = "en-GB"
title = "Gideon Pyzer - Web Developer"
disqusShortname = "gideonpyzer"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-75005144-1"
theme = "hugo-sustain"
pluralizeListTitles = false
enableRobotsTXT = true
canonifyURLs = true
[permalinks]
    post = "/blog/:title/"

[params]
  avatar = "profile.jpg"
  author = "Gideon Pyzer"
  shortTitle = "Gideon Pyzer"
  siteDescription = "I am a London based Front End Web Developer, currently working for Huddle, a cloud-based document collaboration software company."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "gidztech"
  Email         = "gjpyzer@gmail.com"
  Twitter       = "gidztech"
  LinkedIn      = "gideon-pyzer-87a14539"
  Stackoverflow = "users/1814840/gideon-pyzer?tab=profile"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

## Main Menu
[[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"
[[menu.main]]
  name = "Goals"
  weight = 300
  identifier = "goals"
  url = "/goals/"
[[menu.main]]
  name = "Expenses"
  weight = 400
  identifier = "expenses"
  url = "/expenses/"